name: Test Coverage

on:
  push:
    branches:
      - main

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
    - name: Install dependencies
      run: |
        R -e 'install.packages(c("covr", "testthat"))'
    - name: Test with coverage
      run: |
        R -e 'covr::package_coverage()'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
